/* ============================================================
   TRADUÇÕES — PT / EN / FR
   ============================================================ */
window.TRANSLATIONS = {

  /* ── NAVBAR ─────────────────────────────────────── */
  'nav.home':        { pt: 'Início',            en: 'Home',                  fr: 'Accueil' },
  'nav.about':       { pt: 'Sobre',             en: 'About',                 fr: 'À propos' },
  'nav.areas':       { pt: 'Áreas de Atuação',  en: 'Practice Areas',        fr: 'Domaines d\'activité' },
  'nav.articles':    { pt: 'Artigos',           en: 'Articles',              fr: 'Articles' },
  'nav.contacts':    { pt: 'Contactos',         en: 'Contacts',              fr: 'Contacts' },
  'nav.cta':         { pt: 'Agendar Consulta',  en: 'Schedule Consultation',     fr: 'Prendre rendez-vous' },

  /* ── TOP BAR ─────────────────────────────────────── */
  'topbar.location': { pt: 'Lisboa, Portugal',   en: 'Lisboa, Portugal',       fr: 'Lisboa, Portugal' },

  /* ── HERO ────────────────────────────────────────── */
  'hero.eyebrow':    { pt: 'Agência de IA - Portugal', en: 'AI Agency — Lisboa, Portugal', fr: 'Agence IA — Lisbonne, Portugal' },
  'hero.title':      { pt: 'Da estratégia à implementação. <em>IA que cria valor real.</em>', en: 'From strategy to implementation. <em>AI that creates real value.</em>', fr: 'De la stratégie à la mise en œuvre. <em>Une IA qui crée de la valeur réelle.</em>' },
  'hero.sub':        { pt: 'Ajudamos empresas a integrar Inteligência Artificial de forma segura, prática e rentável, transformando desafios em oportunidades de crescimento.', en: 'We help companies integrate Artificial Intelligence in a safe, practical and profitable way, turning challenges into growth opportunities.', fr: 'Nous aidons les entreprises à intégrer l\'Intelligence Artificielle de manière sûre, pratique et rentable, en transformant les défis en opportunités de croissance.' },
  'hero.meta.location': { pt: 'Lisboa, Portugal', en: 'Lisboa, Portugal', fr: 'Lisboa, Portugal' },
  'hero.meta.langs':    { pt: 'PT · EN · FR',     en: 'PT · EN · FR',    fr: 'PT · EN · FR' },
  'hero.btn.book':      { pt: 'Agendar Consulta',   en: 'Book Consultation', fr: 'Prendre rendez-vous' },
  'hero.btn.areas':     { pt: 'Ver Áreas de Atuação', en: 'View Practice Areas', fr: 'Voir les domaines' },
  'hero.btn.session':   { pt: 'Agendar Sessão Estratégica', en: 'Schedule a Strategy Session', fr: 'Planifier une session stratégique' },
  'hero.btn.wa':        { pt: 'Falar por WhatsApp', en: 'Chat on WhatsApp', fr: 'Parler sur WhatsApp' },

  /* ── STATS ───────────────────────────────────────── */
  'stats.years':    { pt: 'Anos de Experiência',    en: 'Years of Experience',   fr: 'Années d\'expérience' },
  'stats.clients':  { pt: 'Clientes Assistidos',    en: 'Clients Assisted',      fr: 'Clients assistés' },
  'stats.areas':    { pt: 'Áreas de Especialidade', en: 'Areas of Expertise',    fr: 'Domaines d\'expertise' },
  'stats.langs':    { pt: 'Idiomas de Atendimento', en: 'Languages of Service',  fr: 'Langues de service' },

  /* ── ABOUT (homepage) ────────────────────────────── */
  'about.eyebrow':  { pt: 'Sobre',  en: 'About Us',  fr: 'À propos' },
  'about.title':    { pt: 'Veio ao sítio certo. Profissionalismo, Confiança e Excelência', en: 'You\'ve come to the right place. Professionalism, Trust and Excellence', fr: 'Vous êtes au bon endroit. Professionnalisme, Confiance et Excellence' },
  'about.p1':       { pt: 'A Pharus AI Agency é especializada na criação de soluções de Inteligência Artificial que transformam a forma como as empresas operam, comunicam e crescem.', en: 'Pharus AI Agency specialises in creating Artificial Intelligence solutions that transform the way companies operate, communicate and grow.', fr: 'Pharus AI Agency est spécialisée dans la création de solutions d\'Intelligence Artificielle qui transforment la façon dont les entreprises opèrent, communiquent et se développent.' },
  'about.p2':       { pt: 'Aliamos experiência em tecnologia, negócios e automação para desenvolver <strong>agentes de IA, assistentes inteligentes, sistemas de geração de conteúdos, automações de processos</strong> e soluções personalizadas capazes de aumentar a produtividade e reduzir custos operacionais.', en: 'We combine expertise in technology, business and automation to develop <strong>AI agents, intelligent assistants, content generation systems, process automations</strong> and personalised solutions capable of increasing productivity and reducing operational costs.', fr: 'Nous combinons une expertise en technologie, en gestion et en automatisation pour développer des <strong>agents IA, des assistants intelligents, des systèmes de génération de contenu, des automatisations de processus</strong> et des solutions personnalisées capables d\'augmenter la productivité et de réduire les coûts opérationnels.' },
  'about.p3':       { pt: 'Trabalhamos com empresas de diferentes setores, ajudando-as a identificar oportunidades de otimização e a implementar soluções inovadoras com impacto real nos resultados. Cada projeto é concebido de forma estratégica, garantindo uma integração eficiente com os processos existentes e uma rápida geração de valor.', en: 'We work with companies from different sectors, helping them identify optimisation opportunities and implement innovative solutions with a real impact on results. Each project is designed strategically, ensuring efficient integration with existing processes and rapid value generation.', fr: 'Nous travaillons avec des entreprises de différents secteurs, en les aidant à identifier des opportunités d\'optimisation et à mettre en œuvre des solutions innovantes ayant un impact réel sur les résultats. Chaque projet est conçu de manière stratégique, garantissant une intégration efficace avec les processus existants et une génération rapide de valeur.' },
  'about.p4':       { pt: 'O nosso compromisso centra-se na excelência, inovação e confiança. Criamos soluções de Inteligência Artificial seguras, escaláveis e orientadas para resultados, permitindo que as organizações se concentrem no que realmente importa: crescer, inovar e liderar o seu mercado.', en: 'Our commitment centres on excellence, innovation and trust. We create safe, scalable and results-oriented Artificial Intelligence solutions, enabling organisations to focus on what truly matters: growing, innovating and leading their market.', fr: 'Notre engagement est axé sur l\'excellence, l\'innovation et la confiance. Nous créons des solutions d\'Intelligence Artificielle sûres, évolutives et orientées résultats, permettant aux organisations de se concentrer sur ce qui compte vraiment : croître, innover et diriger leur marché.' },
  'about.f1':       { pt: 'Atendimento personalizado em Português, Inglês e Francês', en: 'Personalised service in Portuguese, English and French', fr: 'Service personnalisé en portugais, anglais et français' },
  'about.f2':       { pt: 'Da ideia à execução. IA com acompanhamento especializado.', en: 'From idea to execution. AI with expert guidance.', fr: 'De l\'idée à l\'exécution. IA avec accompagnement expert.' },
  'about.f3':       { pt: 'Trabalhamos lado a lado consigo para identificar oportunidades, implementar soluções inteligentes e maximizar resultados.', en: 'We work side by side with you to identify opportunities, implement intelligent solutions and maximise results.', fr: 'Nous travaillons côte à côte avec vous pour identifier les opportunités, mettre en œuvre des solutions intelligentes et maximiser les résultats.' },
  'about.badge':    { pt: 'anos de<br>experiência', en: 'years of<br>experience', fr: 'ans<br>d\'expérience' },
  'about.btn':      { pt: 'Conhecer a Pharus AI Agency', en: 'Meet Pharus AI Agency', fr: 'Découvrir Pharus AI Agency' },

  /* ── AREAS (homepage cards) ──────────────────────── */
  'areas.eyebrow':  { pt: 'O que fazemos',  en: 'What we do',  fr: 'Ce que nous faisons' },
  'areas.title':    { pt: 'Áreas de Especialização', en: 'Areas of Specialisation', fr: 'Domaines de spécialisation' },
  'areas.intro':    { pt: 'Ajudamos empresas a tirar partido da Inteligência Artificial através de:<br><br>• Agentes de IA e Assistentes Virtuais<br>• Automação de Processos Empresariais<br>• Chatbots Inteligentes<br>• IA para Marketing e Vendas<br>• Geração Automática de Conteúdos<br>• Análise de Dados e Business Intelligence<br>• Integração de Sistemas e APIs<br>• Formação e Consultoria em IA<br>• Desenvolvimento de Soluções Personalizadas<br>• Transformação Digital e Inovação Empresarial', en: 'We help companies harness Artificial Intelligence through:<br><br>• AI Agents and Virtual Assistants<br>• Business Process Automation<br>• Intelligent Chatbots<br>• AI for Marketing and Sales<br>• Automatic Content Generation<br>• Data Analytics and Business Intelligence<br>• Systems and API Integration<br>• AI Training and Consulting<br>• Custom Solution Development<br>• Digital Transformation and Business Innovation', fr: 'Nous aidons les entreprises à tirer parti de l\'Intelligence Artificielle grâce à :<br><br>• Agents IA et Assistants Virtuels<br>• Automatisation des Processus Métier<br>• Chatbots Intelligents<br>• IA pour le Marketing et les Ventes<br>• Génération Automatique de Contenus<br>• Analyse de Données et Business Intelligence<br>• Intégration de Systèmes et d\'APIs<br>• Formation et Conseil en IA<br>• Développement de Solutions Personnalisées<br>• Transformation Numérique et Innovation' },
  'area.imob.title': { pt: 'Agentes de Inteligência Artificial', en: 'Artificial Intelligence Agents', fr: 'Agents d\'Intelligence Artificielle' },
  'area.imob.desc':  { pt: 'Desenvolvimento de agentes autónomos capazes de executar tarefas, interagir com clientes, apoiar equipas e automatizar processos empresariais com elevada eficiência.', en: 'Development of autonomous agents capable of executing tasks, interacting with clients, supporting teams and automating business processes with high efficiency.', fr: 'Développement d\'agents autonomes capables d\'exécuter des tâches, d\'interagir avec les clients, d\'accompagner les équipes et d\'automatiser les processus d\'entreprise avec une haute efficacité.' },
  'area.soc.title':  { pt: 'Automação de Processos', en: 'Process Automation', fr: 'Automatisation des processus' },
  'area.soc.desc':   { pt: 'Identificação, otimização e automatização de tarefas repetitivas através de Inteligência Artificial e integração de sistemas, reduzindo custos operacionais e aumentando a produtividade.', en: 'Identification, optimisation and automation of repetitive tasks through Artificial Intelligence and systems integration, reducing operational costs and increasing productivity.', fr: 'Identification, optimisation et automatisation des tâches répétitives grâce à l\'Intelligence Artificielle et à l\'intégration de systèmes, réduisant les coûts opérationnels et augmentant la productivité.' },
  'area.mig.title':  { pt: 'Assistentes Virtuais e Chatbots', en: 'Virtual Assistants & Chatbots', fr: 'Assistants virtuels et chatbots' },
  'area.mig.desc':   { pt: 'Criação de assistentes inteligentes para websites, atendimento ao cliente, suporte técnico e equipas internas, disponíveis 24 horas por dia.', en: 'Creation of intelligent assistants for websites, customer service, technical support and internal teams, available 24 hours a day.', fr: 'Création d\'assistants intelligents pour les sites web, le service client, le support technique et les équipes internes, disponibles 24 heures sur 24.' },
  'area.nac.title':  { pt: 'Estratégia e Consultoria em IA', en: 'AI Strategy & Consulting', fr: 'Stratégie et conseil en IA' },
  'area.nac.desc':   { pt: 'Definição de estratégias de adoção de Inteligência Artificial alinhadas com os objetivos do negócio. Avaliação de oportunidades, desenho de soluções e acompanhamento da implementação.', en: 'Defining Artificial Intelligence adoption strategies aligned with business objectives. Opportunity assessment, solution design and implementation support.', fr: 'Définition de stratégies d\'adoption de l\'Intelligence Artificielle alignées sur les objectifs de l\'entreprise. Évaluation des opportunités, conception de solutions et accompagnement à la mise en œuvre.' },

  /* ── WHY SECTION ─────────────────────────────────── */
  'why.eyebrow':    { pt: 'Porque Nos Escolher',   en: 'Why Choose Us',          fr: 'Pourquoi nous choisir' },
  'why.title':      { pt: 'Porque Escolher a Pharus AI Agency?', en: 'Why Choose Pharus AI Agency?', fr: 'Pourquoi choisir Pharus AI Agency ?' },
  'why.c1.title':   { pt: 'Experiência e Conhecimento Especializado', en: 'Experience & Specialist Knowledge', fr: 'Expérience et expertise spécialisée' },
  'why.c1.desc':    { pt: 'Combinamos experiência empresarial, tecnológica e estratégica para desenvolver soluções de Inteligência Artificial que geram resultados concretos. Aplicamos as melhores práticas do mercado e as tecnologias mais avançadas para responder aos desafios específicos de cada organização.', en: 'We combine business, technological and strategic expertise to develop AI solutions that generate concrete results. We apply best market practices and the most advanced technologies to address each organisation\'s specific challenges.', fr: 'Nous combinons une expertise en affaires, technologique et stratégique pour développer des solutions IA qui génèrent des résultats concrets. Nous appliquons les meilleures pratiques du marché et les technologies les plus avancées pour répondre aux défis spécifiques de chaque organisation.' },
  'why.c2.title':   { pt: 'Soluções Personalizadas', en: 'Tailored Solutions', fr: 'Solutions personnalisées' },
  'why.c2.desc':    { pt: 'Cada empresa tem objetivos, processos e desafios próprios. Desenvolvemos soluções de IA adaptadas à realidade de cada cliente, garantindo uma implementação alinhada com as necessidades do negócio e um retorno mensurável do investimento.', en: 'Every company has its own objectives, processes and challenges. We develop AI solutions adapted to each client\'s reality, ensuring implementation aligned with business needs and a measurable return on investment.', fr: 'Chaque entreprise a ses propres objectifs, processus et défis. Nous développons des solutions IA adaptées à la réalité de chaque client, garantissant une mise en œuvre alignée sur les besoins de l\'entreprise et un retour sur investissement mesurable.' },
  'why.c3.title':   { pt: 'Acompanhamento Próximo', en: 'Close Support', fr: 'Accompagnement étroit' },
  'why.c3.desc':    { pt: 'Acompanhamos cada projeto desde a análise inicial até à implementação e evolução contínua das soluções. Trabalhamos em estreita colaboração com os nossos clientes para assegurar uma adoção eficaz e uma geração de valor sustentada.', en: 'We accompany each project from initial analysis through to implementation and continuous evolution of solutions. We work in close collaboration with our clients to ensure effective adoption and sustained value generation.', fr: 'Nous accompagnons chaque projet depuis l\'analyse initiale jusqu\'à la mise en œuvre et l\'évolution continue des solutions. Nous travaillons en étroite collaboration avec nos clients pour assurer une adoption efficace et une génération de valeur durable.' },
  'why.phone.label': { pt: 'Contacto directo com a nossa equipa', en: 'Direct contact with our team', fr: 'Contact direct avec notre équipe' },
  'why.or':          { pt: 'ou', en: 'or', fr: 'ou' },
  'why.panel.title': { pt: 'Fale com um Especialista em Inteligência Artificial', en: 'Speak to an AI Specialist', fr: 'Parler à un spécialiste en IA' },
  'why.panel.btn':   { pt: 'Agendar via WhatsApp', en: 'Schedule via WhatsApp', fr: 'Réserver via WhatsApp' },
  'why.tagline':     { pt: 'Transformamos a sua empresa com Inteligência Artificial', en: 'We transform your business with Artificial Intelligence', fr: 'Nous transformons votre entreprise avec l\'Intelligence Artificielle' },

  /* ── TESTIMONIALS ────────────────────────────────── */
  'test.eyebrow':   { pt: 'Testemunhos',                  en: 'Testimonials',               fr: 'Témoignages' },
  'test.title':     { pt: 'O que dizem os nossos clientes', en: 'What our clients say',       fr: 'Ce que disent nos clients' },
  'test.t1.text':   { pt: 'A implementação dos agentes de Inteligência Artificial desenvolvidos pela Pharus AI Agency permitiu-nos reduzir tarefas repetitivas, acelerar processos internos e melhorar a experiência dos nossos clientes. O acompanhamento foi exemplar durante todo o projeto.', en: 'The implementation of the Artificial Intelligence agents developed by Pharus AI Agency allowed us to reduce repetitive tasks, accelerate internal processes and improve our clients\' experience. The support was exemplary throughout the project.', fr: 'La mise en œuvre des agents d\'Intelligence Artificielle développés par Pharus AI Agency nous a permis de réduire les tâches répétitives, d\'accélérer les processus internes et d\'améliorer l\'expérience de nos clients. L\'accompagnement a été exemplaire tout au long du projet.' },
  'test.t1.role':   { pt: 'Diretora Executiva', en: 'Executive Director', fr: 'Directrice Exécutive' },
  'test.t2.text':   { pt: 'O que mais valorizámos foi a capacidade de compreender rapidamente o nosso negócio e transformar desafios operacionais em soluções práticas. A Pharus AI Agency entrega tecnologia com impacto real nos resultados.', en: 'What we valued most was the ability to quickly understand our business and transform operational challenges into practical solutions. Pharus AI Agency delivers technology with a real impact on results.', fr: 'Ce que nous avons le plus apprécié, c\'est la capacité à comprendre rapidement notre activité et à transformer les défis opérationnels en solutions pratiques. Pharus AI Agency livre une technologie ayant un impact réel sur les résultats.' },
  'test.t2.role':   { pt: 'Sócio-Gerente', en: 'Managing Partner', fr: 'Associé-Gérant' },
  'test.t3.text':   { pt: 'A colaboração com a Pharus AI Agency trouxe um impacto imediato à nossa organização. Conseguimos automatizar tarefas críticas, melhorar a eficiência operacional e libertar recursos para atividades de maior valor acrescentado. Recomendo vivamente os seus serviços a qualquer empresa que pretenda tirar partido da Inteligência Artificial de forma estratégica e segura.', en: 'Our collaboration with Pharus AI Agency brought an immediate impact to our organisation. We were able to automate critical tasks, improve operational efficiency and free up resources for higher value-added activities. I strongly recommend their services to any company wishing to leverage Artificial Intelligence in a strategic and safe way.', fr: 'La collaboration avec Pharus AI Agency a eu un impact immédiat sur notre organisation. Nous avons pu automatiser des tâches critiques, améliorer l\'efficacité opérationnelle et libérer des ressources pour des activités à plus forte valeur ajoutée. Je recommande vivement leurs services à toute entreprise souhaitant tirer parti de l\'Intelligence Artificielle de manière stratégique et sécurisée.' },
  'test.t3.role':   { pt: 'CEO', en: 'CEO', fr: 'CEO' },
  'test.t4.text':   { pt: 'A Pharus AI Agency distingue-se pela competência técnica, visão estratégica e capacidade de execução. Cada recomendação apresentada teve um objetivo claro e um impacto mensurável nos nossos resultados. Encontrámos um parceiro tecnológico de confiança para a nossa transformação digital.', en: 'Pharus AI Agency stands out for its technical competence, strategic vision and execution capability. Every recommendation made had a clear objective and a measurable impact on our results. We found a trusted technology partner for our digital transformation.', fr: 'Pharus AI Agency se distingue par sa compétence technique, sa vision stratégique et sa capacité d\'exécution. Chaque recommandation formulée avait un objectif clair et un impact mesurable sur nos résultats. Nous avons trouvé un partenaire technologique de confiance pour notre transformation numérique.' },
  'test.t4.role':   { pt: 'Diretor-Geral', en: 'General Manager', fr: 'Directeur Général' },
  'test.t5.text':   { pt: 'A Pharus AI Agency transformou a forma como a nossa empresa trabalha. As soluções implementadas aumentaram significativamente a produtividade da equipa e permitiram automatizar processos que consumiam muitas horas de trabalho. Uma equipa competente, inovadora e focada em resultados.', en: 'Pharus AI Agency transformed the way our company works. The solutions implemented significantly increased team productivity and allowed us to automate processes that consumed many hours of work. A competent, innovative team focused on results.', fr: 'Pharus AI Agency a transformé la façon dont notre entreprise travaille. Les solutions mises en œuvre ont considérablement augmenté la productivité de l\'équipe et permis d\'automatiser des processus qui consommaient de nombreuses heures de travail. Une équipe compétente, innovante et axée sur les résultats.' },
  'test.t5.role':   { pt: 'Diretora de Operações', en: 'Operations Director', fr: 'Directrice des Opérations' },
  'test.t6.text':   { pt: 'Agradeço à equipa da Pharus AI Agency pela proximidade, profissionalismo e capacidade de encontrar soluções eficazes para os nossos desafios. Desde o primeiro contacto até à implementação final, recebemos acompanhamento permanente e um elevado nível de conhecimento técnico. Foi um prazer trabalhar com uma equipa tão dedicada e orientada para resultados.', en: 'I thank the Pharus AI Agency team for their closeness, professionalism and ability to find effective solutions to our challenges. From the first contact to the final implementation, we received ongoing support and a high level of technical knowledge. It was a pleasure working with such a dedicated and results-oriented team.', fr: 'Je remercie l\'équipe de Pharus AI Agency pour sa proximité, son professionnalisme et sa capacité à trouver des solutions efficaces à nos défis. Du premier contact à la mise en œuvre finale, nous avons bénéficié d\'un accompagnement permanent et d\'un niveau élevé de connaissances techniques. Ce fut un plaisir de travailler avec une équipe si dévouée et orientée vers les résultats.' },
  'test.t6.role':   { pt: 'Administrador', en: 'Administrator', fr: 'Administrateur' },

  /* ── CTA BANNER ──────────────────────────────────── */
  'cta.eyebrow':    { pt: 'Pronto para transformar o seu negócio com Inteligência Artificial?', en: 'Ready to transform your business with Artificial Intelligence?', fr: 'Prêt à transformer votre entreprise avec l\'Intelligence Artificielle ?' },
  'cta.title':      { pt: 'Procura soluções de IA que gerem resultados reais?', en: 'Looking for AI solutions that generate real results?', fr: 'Vous cherchez des solutions IA qui génèrent des résultats réels ?' },
  'cta.desc':       { pt: 'Entre em contacto connosco hoje e descubra como podemos ajudar a automatizar processos, aumentar a produtividade e acelerar o crescimento da sua organização através de soluções de Inteligência Artificial seguras, eficazes e adaptadas às suas necessidades.', en: 'Contact us today and discover how we can help automate processes, increase productivity and accelerate the growth of your organisation through safe, effective and tailored Artificial Intelligence solutions.', fr: 'Contactez-nous aujourd\'hui et découvrez comment nous pouvons vous aider à automatiser les processus, augmenter la productivité et accélérer la croissance de votre organisation grâce à des solutions d\'Intelligence Artificielle sûres, efficaces et adaptées à vos besoins.' },
  'cta.btn.book':   { pt: 'Agendar Consulta',     en: 'Book Consultation',   fr: 'Prendre rendez-vous' },
  'cta.btn.msg':    { pt: 'Enviar Mensagem',       en: 'Send Message',        fr: 'Envoyer un message' },

  /* ── FOOTER ──────────────────────────────────────── */
  'footer.tagline': { pt: 'Pharus AI Agency especializada em Inteligência Artificial, Automação, Agentes Inteligentes e Transformação Digital. Lisboa, Portugal.', en: 'Pharus AI Agency specialised in Artificial Intelligence, Automation, Intelligent Agents and Digital Transformation. Lisboa, Portugal.', fr: 'Pharus AI Agency spécialisée en Intelligence Artificielle, Automatisation, Agents Intelligents et Transformation Numérique. Lisbonne, Portugal.' },
  'footer.nav':     { pt: 'Navegação',     en: 'Navigation',    fr: 'Navigation' },
  'footer.spec':    { pt: 'Serviços', en: 'Services', fr: 'Services' },
  'footer.srv1':    { pt: 'Diagnóstico de oportunidades de implementação de IA ética', en: 'Ethical AI implementation opportunity assessment', fr: 'Diagnostic d\'opportunités de mise en œuvre de l\'IA éthique' },
  'footer.srv2':    { pt: 'Planeamento de arquitetura de copilotos e agentes', en: 'Copilot and agent architecture planning', fr: 'Planification de l\'architecture de copilotos et d\'agents' },
  'footer.srv3':    { pt: 'Formação a equipas para uso eficaz de IA', en: 'Team training for effective AI use', fr: 'Formation des équipes à l\'utilisation efficace de l\'IA' },
  'footer.srv4':    { pt: 'Desenvolvimento de dashboards, apps e websites', en: 'Development of dashboards, apps and websites', fr: 'Développement de tableaux de bord, d\'applications et de sites web' },
  'footer.contacts':{ pt: 'Contactos',     en: 'Contacts',      fr: 'Contacts' },
  'footer.copy':    { pt: '© 2026 Pharus AI Agency · Todos os direitos reservados', en: '© 2026 Pharus AI Agency · All rights reserved', fr: '© 2026 Pharus AI Agency · Tous droits réservés' },
  'footer.privacy': { pt: 'Política de Privacidade', en: 'Privacy Policy', fr: 'Politique de confidentialité' },
  'footer.terms':   { pt: 'Termos e Condições', en: 'Terms and Conditions', fr: 'Termes et conditions' },

  /* ── SOBRE PAGE ──────────────────────────────────── */
  'sobre.eyebrow':  { pt: 'Equipa',                en: 'Team',                  fr: 'Équipe' },
  'sobre.title':    { pt: 'Sobre Nós',             en: 'About Us',              fr: 'À propos de nous' },
  'sobre.founder.eyebrow': { pt: 'MsC Engenheiro', en: 'MsC Engineer', fr: 'MsC Ingénieur' },
  'sobre.founder.title':   { pt: 'Engenheiro - Ordem dos Engenheiros', en: 'Engineer - Order of Engineers', fr: 'Ingénieur - Ordre des Ingénieurs' },
  'sobre.p1': { pt: 'A Pharus AI Agency ajuda empresas a transformar o potencial da Inteligência Artificial em resultados concretos.', en: 'Pharus AI Agency helps companies transform the potential of Artificial Intelligence into concrete results.', fr: 'Pharus AI Agency aide les entreprises à transformer le potentiel de l\'Intelligence Artificielle en résultats concrets.' },
  'sobre.p2': { pt: 'Especializamo-nos na conceção e implementação de agentes inteligentes, automações empresariais, assistentes virtuais, dashboards, aplicações e soluções digitais que simplificam operações e aumentam a eficiência organizacional.', en: 'We specialise in the design and implementation of intelligent agents, business automations, virtual assistants, dashboards, applications and digital solutions that simplify operations and increase organisational efficiency.', fr: 'Nous sommes spécialisés dans la conception et la mise en œuvre d\'agents intelligents, d\'automatisations d\'entreprise, d\'assistants virtuels, de tableaux de bord, d\'applications et de solutions numériques qui simplifient les opérations et augmentent l\'efficacité organisationnelle.' },
  'sobre.p3': { pt: 'Combinamos experiência em engenharia, sistemas de informação, gestão empresarial e inovação tecnológica para desenvolver soluções que respondem aos desafios reais das organizações.', en: 'We combine expertise in engineering, information systems, business management and technological innovation to develop solutions that address the real challenges of organisations.', fr: 'Nous combinons une expertise en ingénierie, systèmes d\'information, gestion d\'entreprise et innovation technologique pour développer des solutions qui répondent aux défis réels des organisations.' },
  'sobre.p4': { pt: 'Cada projeto é construído sobre três pilares fundamentais: estratégia, tecnologia e resultados. O objetivo consiste em criar soluções escaláveis, seguras e capazes de gerar valor sustentável a longo prazo.', en: 'Each project is built on three fundamental pillars: strategy, technology and results. The aim is to create scalable, secure solutions capable of generating sustainable long-term value.', fr: 'Chaque projet est construit sur trois piliers fondamentaux : stratégie, technologie et résultats. L\'objectif consiste à créer des solutions évolutives, sécurisées et capables de générer une valeur durable à long terme.' },
  'sobre.p5': { pt: 'Prestamos apoio a clientes nacionais e internacionais em Português, Inglês e Francês, assegurando uma colaboração eficaz em ambientes empresariais multiculturais.', en: 'We support national and international clients in Portuguese, English and French, ensuring effective collaboration in multicultural business environments.', fr: 'Nous accompagnons des clients nationaux et internationaux en portugais, anglais et français, assurant une collaboration efficace dans des environnements d\'entreprise multiculturels.' },
  'sobre.values.eyebrow': { pt: 'Os Nossos Valores', en: 'Our Values',    fr: 'Nos valeurs' },
  'sobre.values.title':   { pt: 'O que nos define',  en: 'What defines us', fr: 'Ce qui nous définit' },
  'sobre.v1.title': { pt: 'Integridade',  en: 'Integrity',    fr: 'Intégrité' },
  'sobre.v1.desc':  { pt: 'Atuamos sempre com honestidade e transparência, colocando os interesses do cliente em primeiro lugar e garantindo uma relação de total confiança.', en: 'We always act with honesty and transparency, putting the client\'s interests first and ensuring a relationship of complete trust.', fr: 'Nous agissons toujours avec honnêteté et transparence, plaçant les intérêts du client en premier et garantissant une relation de totale confiance.' },
  'sobre.v2.title': { pt: 'Excelência',   en: 'Excellence',   fr: 'Excellence' },
  'sobre.v2.desc':  { pt: 'Assumimos um compromisso permanente com a inovação, a qualidade e a melhoria contínua, integrando os avanços mais recentes em Inteligência Artificial para garantir soluções modernas, eficazes e preparadas para o futuro.', en: 'We make a permanent commitment to innovation, quality and continuous improvement, integrating the latest advances in Artificial Intelligence to ensure modern, effective and future-ready solutions.', fr: 'Nous prenons un engagement permanent envers l\'innovation, la qualité et l\'amélioration continue, en intégrant les dernières avancées en Intelligence Artificielle pour garantir des solutions modernes, efficaces et prêtes pour l\'avenir.' },
  'sobre.v3.title': { pt: 'Proximidade',  en: 'Proximity',    fr: 'Proximité' },
  'sobre.v3.desc':  { pt: 'Cada cliente recebe atenção individualizada. Acompanhamos cada processo de perto, mantendo o cliente informado em cada etapa.', en: 'Each client receives individual attention. We monitor every case closely, keeping the client informed at every step.', fr: 'Chaque client reçoit une attention individualisée. Nous suivons chaque dossier de près, tenant le client informé à chaque étape.' },
  'sobre.cta.title': { pt: 'Precisa de apoio jurídico especializado?', en: 'Do you need specialist legal support?', fr: 'Avez-vous besoin d\'un soutien juridique spécialisé ?' },
  'sobre.cta.desc':  { pt: 'A nossa equipa está disponível para o ajudar. Contacte-nos e agende a sua consulta.', en: 'Our team is available to help you. Contact us and book your consultation.', fr: 'Notre équipe est disponible pour vous aider. Contactez-nous et réservez votre consultation.' },

  /* ── ÁREAS PAGE ──────────────────────────────────── */
  'areas.page.eyebrow': { pt: 'Especialidades', en: 'Specialities', fr: 'Spécialités' },
  'areas.page.title':   { pt: 'Áreas de Atuação',  en: 'Practice Areas', fr: 'Domaines d\'activité' },
  'areas.page.intro':   { pt: 'Desenvolvemos soluções de Inteligência Artificial, automação e inovação digital para empresas que procuram crescer, otimizar processos e aumentar a sua competitividade.', en: 'We develop Artificial Intelligence, automation and digital innovation solutions for companies seeking to grow, optimise processes and increase their competitiveness.', fr: 'Nous développons des solutions d\'Intelligence Artificielle, d\'automatisation et d\'innovation numérique pour les entreprises souhaitant croître, optimiser leurs processus et accroître leur compétitivité.' },
  'areas.page.cta.title': { pt: 'Cada empresa tem oportunidades únicas para aplicar Inteligência Artificial.', en: 'Every company has unique opportunities to apply Artificial Intelligence.', fr: 'Chaque entreprise a des opportunités uniques pour appliquer l\'Intelligence Artificielle.' },
  'areas.page.cta.desc':  { pt: 'Agende uma reunião com a Pharus AI Agency e descubra onde a automação, os agentes inteligentes e as soluções de IA podem gerar mais valor para o seu negócio.', en: 'Schedule a meeting with Pharus AI Agency and discover where automation, intelligent agents and AI solutions can generate the most value for your business.', fr: 'Planifiez une réunion avec Pharus AI Agency et découvrez où l\'automatisation, les agents intelligents et les solutions IA peuvent générer le plus de valeur pour votre entreprise.' },

  /* ── ARTIGOS PAGE ────────────────────────────────── */
  'art.eyebrow':    { pt: 'Conhecimento Jurídico',  en: 'Legal Knowledge',    fr: 'Connaissances juridiques' },
  'art.d1': { pt: '15 de Maio, 2026',       en: '15 May 2026',       fr: '15 mai 2026' },
  'art.d2': { pt: '3 de Abril, 2026',       en: '3 April 2026',      fr: '3 avril 2026' },
  'art.d3': { pt: '18 de Março, 2026',      en: '18 March 2026',     fr: '18 mars 2026' },
  'art.d4': { pt: '2 de Fevereiro, 2026',   en: '2 February 2026',   fr: '2 février 2026' },
  'art.d5': { pt: '10 de Janeiro, 2026',    en: '10 January 2026',   fr: '10 janvier 2026' },
  'art.d6': { pt: '5 de Dezembro, 2025',    en: '5 December 2025',   fr: '5 décembre 2025' },
  'art.title':      { pt: 'Artigos & Publicações',  en: 'Articles & Publications', fr: 'Articles & Publications' },
  'art.intro':      { pt: 'Partilhamos conhecimento jurídico atualizado para ajudar os nossos clientes a navegar pelo sistema legal português.', en: 'We share up-to-date legal knowledge to help our clients navigate the Portuguese legal system.', fr: 'Nous partageons des connaissances juridiques actualisées pour aider nos clients à naviguer dans le système juridique portugais.' },
  'art.cta.title':  { pt: 'Tem questões jurídicas específicas?', en: 'Do you have specific legal questions?', fr: 'Avez-vous des questions juridiques spécifiques ?' },
  'art.cta.desc':   { pt: 'Não encontrou o que procurava? Contacte-nos directamente e a nossa equipa terá todo o gosto em esclarecer as suas dúvidas.', en: 'Didn\'t find what you were looking for? Contact us directly and our team will be happy to answer your questions.', fr: 'Vous n\'avez pas trouvé ce que vous cherchiez ? Contactez-nous directement et notre équipe se fera un plaisir de répondre à vos questions.' },
  'art.cta.lawyer': { pt: 'Falar com um Advogado', en: 'Speak to a Lawyer', fr: 'Parler à un avocat' },
  'art.tag.imob':   { pt: 'Direito Imobiliário',   en: 'Property Law',      fr: 'Droit immobilier' },
  'art.tag.mig':    { pt: 'Direito Migratório',    en: 'Immigration Law',   fr: 'Droit de l\'immigration' },
  'art.tag.nac':    { pt: 'Nacionalidade',         en: 'Nationality',       fr: 'Nationalité' },
  'art.tag.soc':    { pt: 'Sociedades',            en: 'Companies',         fr: 'Sociétés' },
  'art.readmore':   { pt: 'Ler mais',              en: 'Read more',         fr: 'Lire la suite' },

  /* ── WIDGET DE CONTACTO INTELIGENTE ─────────────── */
  'cont.goal.eyebrow':   { pt: 'Primeiro passo', en: 'First step', fr: 'Première étape' },
  'cont.goal.title':     { pt: 'Como o podemos ajudar?', en: 'How can we help you?', fr: 'Comment pouvons-nous vous aider ?' },
  'cont.goal.sub':       { pt: 'Selecione o que melhor descreve o seu objetivo e receba as opções mais adequadas.', en: 'Select what best describes your goal and receive the most suitable options.', fr: 'Sélectionnez ce qui décrit le mieux votre objectif et recevez les options les plus adaptées.' },
  'cont.goal.automation':{ pt: 'Quero automatizar processos', en: 'I want to automate processes', fr: 'Je veux automatiser des processus' },
  'cont.goal.agent':     { pt: 'Quero criar um Agente IA', en: 'I want to create an AI Agent', fr: 'Je veux créer un Agent IA' },
  'cont.goal.chatbot':   { pt: 'Quero um Chatbot', en: 'I want a Chatbot', fr: 'Je veux un Chatbot' },
  'cont.goal.training':  { pt: 'Quero formação em IA', en: 'I want AI training', fr: 'Je veux une formation en IA' },
  'cont.goal.proposal':  { pt: 'Quero uma proposta', en: 'I want a proposal', fr: 'Je veux une proposition' },
  'cont.goal.btnWa':     { pt: 'Iniciar no WhatsApp', en: 'Start on WhatsApp', fr: 'Démarrer sur WhatsApp' },
  'cont.goal.btnCal':    { pt: 'Agendar Reunião', en: 'Schedule a Meeting', fr: 'Planifier une réunion' },
  'cont.goal.btnProposal':{ pt: 'Solicitar Proposta', en: 'Request a Proposal', fr: 'Demander une proposition' },

  /* ── FORMULÁRIO DE QUALIFICAÇÃO ──────────────────── */
  'cont.form.company':   { pt: 'Empresa *', en: 'Company *', fr: 'Entreprise *' },
  'cont.form.employees': { pt: 'Nº de Colaboradores', en: 'Number of Employees', fr: 'Nombre de collaborateurs' },
  'cont.form.sector':    { pt: 'Setor de Atividade', en: 'Industry Sector', fr: 'Secteur d\'activité' },
  'cont.form.objective': { pt: 'Objetivo Pretendido *', en: 'Intended Objective *', fr: 'Objectif souhaité *' },
  'cont.form.budget':    { pt: 'Orçamento Previsto', en: 'Estimated Budget', fr: 'Budget prévu' },
  'cont.form.challenge': { pt: 'Principal Desafio / Contexto *', en: 'Main Challenge / Context *', fr: 'Principal défi / Contexte *' },

  /* ── CONTACTOS PAGE ──────────────────────────────── */
  'cont.eyebrow':   { pt: 'Fale Connosco', en: 'Get in Touch', fr: 'Contactez-nous' },
  'cont.title':     { pt: 'Contactos',              en: 'Contacts',              fr: 'Contacts' },
  'cont.info.eyebrow': { pt: 'Informações',         en: 'Information',           fr: 'Informations' },
  'cont.info.title':   { pt: 'Como nos pode encontrar', en: 'How to find us',    fr: 'Comment nous trouver' },
  'cont.address.label':  { pt: 'Morada',    en: 'Address',    fr: 'Adresse' },
  'cont.phone.label':    { pt: 'Telefone / WhatsApp', en: 'Phone / WhatsApp', fr: 'Téléphone / WhatsApp' },
  'cont.email.label':    { pt: 'Email',     en: 'Email',      fr: 'E-mail' },
  'cont.hours.label':    { pt: 'Horário de Atendimento', en: 'Opening Hours', fr: 'Heures d\'ouverture' },
  'cont.hours.value':    { pt: 'Deixe mensagem e respondemos de forma célere.', en: 'Leave a message and we will respond promptly.', fr: 'Laissez un message et nous répondrons rapidement.' },
  'cont.btn.wa':    { pt: 'Contactar via WhatsApp', en: 'Contact via WhatsApp', fr: 'Contacter via WhatsApp' },
  'cont.btn.email': { pt: 'Enviar E-mail',          en: 'Send Email',           fr: 'Envoyer un e-mail' },
  'cont.follow':    { pt: 'Siga-nos',               en: 'Follow us',            fr: 'Suivez-nous' },
  'cont.form.title':{ pt: 'Envie-nos uma Mensagem', en: 'Send us a Message',    fr: 'Envoyez-nous un message' },
  'cont.form.sub':  { pt: 'A mensagem será enviada directamente para o nosso email.', en: 'The message will be sent directly to our email.', fr: 'Le message sera envoyé directement à notre e-mail.' },
  'cont.form.name': { pt: 'Nome *',      en: 'First Name *', fr: 'Prénom *' },
  'cont.form.surname': { pt: 'Apelido *', en: 'Surname *',  fr: 'Nom *' },
  'cont.form.email':{ pt: 'Email *',     en: 'Email *',      fr: 'E-mail *' },
  'cont.form.phone':{ pt: 'Telefone',    en: 'Phone',        fr: 'Téléphone' },
  'cont.form.area': { pt: 'Área de Interesse', en: 'Area of Interest', fr: 'Domaine d\'intérêt' },
  'cont.form.msg':  { pt: 'Mensagem *',  en: 'Message *',    fr: 'Message *' },
  'cont.form.send': { pt: 'Enviar Mensagem', en: 'Send Message', fr: 'Envoyer le message' },
  'cont.map.title': { pt: 'Lisboa, Portugal', en: 'Lisboa, Portugal', fr: 'Lisboa, Portugal' },
  'cont.map.addr':  { pt: 'Lisboa, Portugal', en: 'Lisboa, Portugal', fr: 'Lisbonne, Portugal' },
  'cont.map.btn':   { pt: 'Ver no Google Maps', en: 'View on Google Maps', fr: 'Voir sur Google Maps' },
  'cont.cta.title': { pt: 'Pronto para resolver o seu caso?', en: 'Ready to resolve your case?', fr: 'Prêt à résoudre votre affaire ?' },
  'cont.cta.desc':  { pt: 'Contacte-nos hoje e descubra como podemos ajudar.', en: 'Contact us today and find out how we can help.', fr: 'Contactez-nous aujourd\'hui et découvrez comment nous pouvons vous aider.' },

  /* ── SOBRE BIO EXPAND ────────────────────────────── */
  'sobre.bio1': { pt: 'Sou Engenheiro de Sistemas e Computadores pelo Instituto Superior Técnico. Possuo formação avançada em gestão, energia, inovação tecnológica e Inteligência Artificial. Ao longo da minha carreira, lidero projetos empresariais em diferentes setores, sempre com um foco claro na criação de valor através da tecnologia.', en: 'I am a Computer and Systems Engineer from Instituto Superior Técnico. I have advanced training in management, energy, technological innovation and Artificial Intelligence. Throughout my career, I have led business projects across different sectors, always with a clear focus on creating value through technology.', fr: 'Je suis Ingénieur en Systèmes Informatiques de l\'Instituto Superior Técnico. Je possède une formation avancée en gestion, énergie, innovation technologique et Intelligence Artificielle. Tout au long de ma carrière, j\'ai dirigé des projets d\'entreprise dans différents secteurs, toujours avec un objectif clair de création de valeur par la technologie.' },
  'sobre.bio2': { pt: 'Hoje dedico-me a ajudar empresas a aproveitar o potencial da Inteligência Artificial para automatizar processos, aumentar a eficiência operacional e acelerar o crescimento.', en: 'Today I dedicate myself to helping companies harness the potential of Artificial Intelligence to automate processes, increase operational efficiency and accelerate growth.', fr: 'Aujourd\'hui, je me consacre à aider les entreprises à exploiter le potentiel de l\'Intelligence Artificielle pour automatiser les processus, augmenter l\'efficacité opérationnelle et accélérer la croissance.' },
  'sobre.bio3': { pt: 'Acredito que a tecnologia só faz sentido quando resolve problemas reais. Por isso, cada solução que desenvolvo parte de uma compreensão profunda do negócio, dos seus desafios e dos seus objetivos.', en: 'I believe technology only makes sense when it solves real problems. That is why every solution I develop starts from a deep understanding of the business, its challenges and its objectives.', fr: 'Je crois que la technologie n\'a de sens que lorsqu\'elle résout de vrais problèmes. C\'est pourquoi chaque solution que je développe part d\'une compréhension approfondie de l\'entreprise, de ses défis et de ses objectifs.' },
  'sobre.bio4': { pt: 'Através da Pharus AI Agency, combino experiência empresarial, conhecimento tecnológico e visão estratégica para criar soluções de IA que transformam organizações e geram resultados mensuráveis.', en: 'Through Pharus AI Agency, I combine business experience, technological knowledge and strategic vision to create AI solutions that transform organisations and generate measurable results.', fr: 'À travers Pharus AI Agency, je combine expérience professionnelle, savoir-faire technologique et vision stratégique pour créer des solutions IA qui transforment les organisations et génèrent des résultats mesurables.' },
  'sobre.bio5': { pt: 'O compromisso mantém-se inalterado: entregar inovação com propósito, tecnologia com impacto e soluções que ajudam os clientes a alcançar os seus objetivos com maior rapidez, eficiência e confiança.', en: 'The commitment remains unchanged: to deliver innovation with purpose, technology with impact and solutions that help clients achieve their goals with greater speed, efficiency and confidence.', fr: 'L\'engagement reste inchangé : livrer de l\'innovation avec un objectif, de la technologie avec un impact et des solutions qui aident les clients à atteindre leurs objectifs avec plus de rapidité, d\'efficacité et de confiance.' },
  'sobre.exp':       { pt: '+25 anos de experiência', en: '+25 years of experience', fr: '+25 ans d\'expérience' },
  'sobre.saberMais': { pt: 'Saber mais...', en: 'Find out more...', fr: 'En savoir plus...' },
  'sobre.saberMenos': { pt: 'Saber menos...', en: 'Show less...', fr: 'Réduire...' },

  /* ── ÁREAS PAGE SERVICE LISTS ────────────────────── */
  'area.imob.li1': { pt: 'Diagnóstico de oportunidades de implementação de IA ética', en: 'Ethical AI implementation opportunity assessment', fr: 'Diagnostic d\'opportunités de mise en œuvre de l\'IA éthique' },
  'area.imob.li2': { pt: 'Planeamento de arquitetura de copilotos e agentes de IA', en: 'Copilot and AI agent architecture planning', fr: 'Planification de l\'architecture de copilotos et d\'agents IA' },
  'area.imob.li3': { pt: 'Formação de equipas para utilização eficaz da Inteligência Artificial', en: 'Team training for effective use of Artificial Intelligence', fr: 'Formation des équipes à l\'utilisation efficace de l\'Intelligence Artificielle' },
  'area.imob.li4': { pt: 'Desenvolvimento de dashboards, aplicações e websites', en: 'Development of dashboards, applications and websites', fr: 'Développement de tableaux de bord, d\'applications et de sites web' },
  'area.soc.li1':    { pt: 'Comportamentos pré-programados (ex: responder clientes, recolher dados, enviar relatórios)', en: 'Pre-programmed behaviours (e.g.: responding to clients, collecting data, sending reports)', fr: 'Comportements préprogrammés (ex : répondre aux clients, collecter des données, envoyer des rapports)' },
  'area.soc.li2':    { pt: 'Workflows inteligentes, reativos e proactivos com tomada de decisão baseada em regras ou IA (ex., agente que monitora e responde clientes automaticamente)', en: 'Intelligent, reactive and proactive workflows with rule-based or AI decision-making (e.g., agent that monitors and responds to clients automatically)', fr: 'Workflows intelligents, réactifs et proactifs avec prise de décision basée sur des règles ou l\'IA (ex., agent qui surveille et répond aux clients automatiquement)' },
  'area.soc.li3':    { pt: 'Integração com APIs e RPA', en: 'API and RPA integration', fr: 'Intégration avec les APIs et RPA' },
  'area.soc.li4':    { pt: 'Agentes IA que fazem pesquisas e criam relatórios de inteligência de mercado', en: 'AI agents that conduct research and create market intelligence reports', fr: 'Agents IA qui effectuent des recherches et créent des rapports d\'intelligence de marché' },
  'area.soc.subhead':{ pt: 'Pacotes de Serviços', en: 'Service Packages', fr: 'Forfaits de services' },
  'area.soc.li5':    { pt: 'Diagnóstico e arquitetura de agentes IA', en: 'AI agent diagnosis and architecture', fr: 'Diagnostic et architecture des agents IA' },
  'area.soc.li6':    { pt: 'Customização de modelos (prompt engineering avançado, fine-tuning, RAG)', en: 'Model customisation (advanced prompt engineering, fine-tuning, RAG)', fr: 'Personnalisation de modèles (prompt engineering avancé, fine-tuning, RAG)' },
  'area.soc.li7':    { pt: 'Treino de equipas para utilização de copilotos', en: 'Team training for copilot use', fr: 'Formation des équipes à l\'utilisation des copilotos' },
  'area.mig.li1':    { pt: 'Comportamentos pré-programados (ex: responder clientes, recolher dados, enviar relatórios)', en: 'Pre-programmed behaviours (e.g.: responding to clients, collecting data, sending reports)', fr: 'Comportements préprogrammés (ex : répondre aux clients, collecter des données, envoyer des rapports)' },
  'area.mig.li2':    { pt: 'Workflows inteligentes, reativos e proactivos com tomada de decisão baseada em regras ou IA (ex., agente que monitora e responde clientes automaticamente)', en: 'Intelligent, reactive and proactive workflows with rule-based or AI decision-making (e.g., agent that monitors and responds to clients automatically)', fr: 'Workflows intelligents, réactifs et proactifs avec prise de décision basée sur des règles ou l\'IA (ex., agent qui surveille et répond aux clients automatiquement)' },
  'area.mig.li3':    { pt: 'Integração com APIs e RPA', en: 'API and RPA integration', fr: 'Intégration avec les APIs et RPA' },
  'area.mig.li4':    { pt: 'Agentes IA que fazem pesquisas e criam relatórios de inteligência de mercado', en: 'AI agents that conduct research and create market intelligence reports', fr: 'Agents IA qui effectuent des recherches et créent des rapports d\'intelligence de marché' },
  'area.nac.li1':    { pt: 'Diagnóstico de oportunidades de automação', en: 'Automation opportunity assessment', fr: 'Diagnostic d\'opportunités d\'automatisation' },
  'area.nac.li2':    { pt: 'Planeamento de arquitectura de copilotos e agentes', en: 'Copilot and agent architecture planning', fr: 'Planification de l\'architecture de copilotos et d\'agents' },
  'area.nac.li3':    { pt: 'Formação a equipas para uso eficaz de IA', en: 'Team training for effective AI use', fr: 'Formation des équipes à l\'utilisation efficace de l\'IA' },

  /* ── ARTIGOS CARDS ───────────────────────────────── */
  'art.a1.title': { pt: 'Guia Completo para Estrangeiros que Querem Comprar Casa em Portugal', en: 'Complete Guide for Foreigners Wishing to Buy a Home in Portugal', fr: 'Guide complet pour les étrangers souhaitant acheter une maison au Portugal' },
  'art.a1.desc':  { pt: 'Tudo o que precisa de saber antes de comprar um imóvel em Portugal: documentação necessária, impostos, due diligence e o papel do advogado no processo.', en: 'Everything you need to know before buying a property in Portugal: required documentation, taxes, due diligence and the role of a lawyer in the process.', fr: 'Tout ce que vous devez savoir avant d\'acheter un bien immobilier au Portugal : documentation requise, impôts, due diligence et le rôle de l\'avocat.' },
  'art.a2.title': { pt: 'Visto D7 em 2026: Requisitos, Processo e Dicas Essenciais', en: 'D7 Visa in 2026: Requirements, Process and Essential Tips', fr: 'Visa D7 en 2026 : Conditions, procédure et conseils essentiels' },
  'art.a2.desc':  { pt: 'O Visto D7 é uma das principais vias de acesso à residência em Portugal para quem tem rendimentos passivos. Saiba como funciona o processo em 2026.', en: 'The D7 Visa is one of the main routes to residency in Portugal for those with passive income. Find out how the process works in 2026.', fr: 'Le Visa D7 est l\'une des principales voies d\'accès à la résidence au Portugal pour ceux qui disposent de revenus passifs. Découvrez comment fonctionne le processus en 2026.' },
  'art.a3.title': { pt: 'Como Obter a Nacionalidade Portuguesa por Ascendência em 2026', en: 'How to Obtain Portuguese Citizenship by Descent in 2026', fr: 'Comment obtenir la nationalité portugaise par filiation en 2026' },
  'art.a3.desc':  { pt: 'Descendente de portugueses? Saiba quais os documentos necessários, os critérios legais e quanto tempo demora o processo de nacionalidade por ascendência.', en: 'A descendant of Portuguese nationals? Find out what documents are required, the legal criteria and how long the citizenship by descent process takes.', fr: 'Descendant de Portugais ? Découvrez les documents nécessaires, les critères légaux et la durée du processus de nationalité par filiation.' },
  'art.a4.title': { pt: 'Como Constituir uma Empresa em Portugal: Passo a Passo', en: 'How to Set Up a Company in Portugal: A Step-by-Step Guide', fr: 'Comment créer une entreprise au Portugal : étape par étape' },
  'art.a4.desc':  { pt: 'Guia prático para empreendedores estrangeiros que querem abrir uma empresa em Portugal. Tipos de sociedades, capital mínimo, prazo e custos envolvidos.', en: 'A practical guide for foreign entrepreneurs wishing to open a company in Portugal. Types of companies, minimum capital, timescales and costs involved.', fr: 'Guide pratique pour les entrepreneurs étrangers souhaitant ouvrir une entreprise au Portugal. Types de sociétés, capital minimum, délais et coûts.' },
  'art.a5.title': { pt: 'IMT e Imposto de Selo na Compra de Imóveis: O que Paga em 2026', en: 'IMT and Stamp Duty when Buying Property: What You Pay in 2026', fr: 'IMT et droit de timbre lors de l\'achat d\'un bien immobilier : ce que vous payez en 2026' },
  'art.a5.desc':  { pt: 'Entenda os impostos que incidem sobre a compra de imóveis em Portugal, como o IMT e o Imposto de Selo, com tabelas e exemplos práticos de cálculo.', en: 'Understand the taxes applicable to property purchases in Portugal, such as IMT and Stamp Duty, with tables and practical calculation examples.', fr: 'Comprenez les taxes applicables aux achats immobiliers au Portugal, telles que l\'IMT et le droit de timbre, avec des tableaux et des exemples de calcul.' },
  'art.a6.title': { pt: 'Visto de Nómada Digital em Portugal: Tudo o que Precisa de Saber', en: 'Digital Nomad Visa in Portugal: Everything You Need to Know', fr: 'Visa de Nomade Numérique au Portugal : tout ce que vous devez savoir' },
  'art.a6.desc':  { pt: 'Portugal é um dos destinos preferidos por nómadas digitais. Conheça os requisitos, documentação e processo de candidatura ao visto de nómada digital.', en: 'Portugal is one of the most popular destinations for digital nomads. Find out about the requirements, documentation and application process for the digital nomad visa.', fr: 'Le Portugal est l\'une des destinations préférées des nomades numériques. Découvrez les conditions, la documentation et le processus de candidature au visa.' },

  /* ── CONTACTOS FORM PLACEHOLDERS ─────────────────── */
  'cont.form.name.ph':      { pt: 'O seu nome',    en: 'Your first name',   fr: 'Votre prénom' },
  'cont.form.surname.ph':   { pt: 'O seu apelido', en: 'Your surname',      fr: 'Votre nom' },
  'cont.form.company.ph':   { pt: 'Nome da empresa', en: 'Company name', fr: 'Nom de l\'entreprise' },
  'cont.form.email.ph':     { pt: 'email@empresa.com', en: 'email@company.com', fr: 'email@entreprise.com' },
  'cont.form.phone.ph':     { pt: '+351 912 484 143', en: '+44 000 000 0000', fr: '+33 0 00 00 00 00' },
  'cont.form.msg.ph':       { pt: 'Descreva brevemente a sua situação...', en: 'Briefly describe your situation...', fr: 'Décrivez brièvement votre situation...' },
  'cont.form.area.opt1':    { pt: 'Seleccione uma área...', en: 'Select an area...', fr: 'Sélectionnez un domaine...' },
  'cont.form.select.ph':    { pt: 'Selecione...', en: 'Select...', fr: 'Sélectionner...' },
  'cont.form.objective.ph': { pt: 'Selecione o principal objetivo...', en: 'Select the main objective...', fr: 'Sélectionner l\'objectif principal...' },
  'cont.form.budget.ph':    { pt: 'Prefiro não indicar', en: 'I prefer not to say', fr: 'Je préfère ne pas indiquer' },
  'cont.form.challenge.ph': { pt: 'Descreva brevemente o seu principal desafio e o que pretende alcançar...', en: 'Briefly describe your main challenge and what you aim to achieve...', fr: 'Décrivez brièvement votre principal défi et ce que vous souhaitez atteindre...' },
  'cont.form.sector.tech':     { pt: 'Tecnologia',              en: 'Technology',               fr: 'Technologie' },
  'cont.form.sector.health':   { pt: 'Saúde',                   en: 'Healthcare',               fr: 'Santé' },
  'cont.form.sector.retail':   { pt: 'Retalho / E-commerce',    en: 'Retail / E-commerce',      fr: 'Commerce de détail / E-commerce' },
  'cont.form.sector.realty':   { pt: 'Imobiliário',             en: 'Real Estate',              fr: 'Immobilier' },
  'cont.form.sector.finance':  { pt: 'Serviços Financeiros',    en: 'Financial Services',       fr: 'Services financiers' },
  'cont.form.sector.edu':      { pt: 'Educação',                en: 'Education',                fr: 'Éducation' },
  'cont.form.sector.industry': { pt: 'Industria / Manufatura',  en: 'Industry / Manufacturing', fr: 'Industrie / Fabrication' },
  'cont.form.sector.tourism':  { pt: 'Turismo / Hotelaria',     en: 'Tourism / Hospitality',    fr: 'Tourisme / Hôtellerie' },
  'cont.form.sector.other':    { pt: 'Outro',                   en: 'Other',                    fr: 'Autre' },
  'cont.form.obj.automate':    { pt: 'Automatizar processos internos',         en: 'Automate internal processes',        fr: 'Automatiser les processus internes' },
  'cont.form.obj.agent':       { pt: 'Criar um Agente de IA',                  en: 'Create an AI Agent',                 fr: 'Créer un agent IA' },
  'cont.form.obj.chatbot':     { pt: 'Implementar um Chatbot',                 en: 'Implement a Chatbot',                fr: 'Mettre en place un Chatbot' },
  'cont.form.obj.training':    { pt: 'Formação em Inteligência Artificial',    en: 'AI Training',                        fr: 'Formation en Intelligence Artificielle' },
  'cont.form.obj.dashboard':   { pt: 'Dashboard / Aplicação / Website',       en: 'Dashboard / Application / Website',  fr: 'Tableau de bord / Application / Site web' },
  'cont.form.obj.strategy':    { pt: 'Estratégia e Consultoria em IA',        en: 'AI Strategy & Consulting',           fr: 'Stratégie et conseil en IA' },
  'cont.form.obj.other':       { pt: 'Outro',                                  en: 'Other',                              fr: 'Autre' },
  'cont.form.budget.opt1':     { pt: 'Menos de €1.000',   en: 'Less than €1,000',    fr: 'Moins de 1 000 €' },
  'cont.form.budget.opt2':     { pt: '€1.000 – €3.000',   en: '€1,000 – €3,000',     fr: '1 000 € – 3 000 €' },
  'cont.form.budget.opt3':     { pt: '€3.000 – €10.000',  en: '€3,000 – €10,000',    fr: '3 000 € – 10 000 €' },
  'cont.form.budget.opt4':     { pt: '€10.000 – €30.000', en: '€10,000 – €30,000',   fr: '10 000 € – 30 000 €' },
  'cont.form.budget.opt5':     { pt: 'Mais de €30.000',   en: 'More than €30,000',   fr: 'Plus de 30 000 €' },
  'cont.hours.value':     { pt: 'Deixe mensagem e respondemos de forma célere.', en: 'Leave a message and we will respond promptly.', fr: 'Laissez un message et nous répondrons rapidement.' },

  /* ── ÁREAS PAGE — CAROUSEL SLIDES (EN/FR) ─────────── */
  'carousel.ia-particulares-empresas.h3': { en: 'Artificial Intelligence for Individuals and Businesses', fr: 'Intelligence Artificielle pour Particuliers et Entreprises' },
  'carousel.ia-particulares-empresas.p':  { en: 'We develop AI solutions tailored to each client\'s needs.', fr: 'Nous développons des solutions IA adaptées aux besoins de chaque client.' },
  'carousel.ia-particulares-empresas.ul': {
    en: '<li class="area-list-subhead">Ready to create your next project?</li><li>Do you want to develop your visual identity, Brand Book and integrate it by creating a website, app, dashboard or AI agent consistent with your brand?</li><li>Do you want to learn to build professional digital solutions using the most advanced tools on the market?</li><li>Schedule a strategic meeting with Pharus AI and discover how to turn an idea into a real product, with professional mentoring of excellence.</li><li class="area-list-subhead">Strategic Consulting</li><li>We help define the best technological strategy for each situation.</li><li class="area-list-subhead">Complete Journey</li><li>From the company\'s Visual Identity, Brand Book, to Design, to the creation of a website, app or dashboard, to Deploy and the strategy, implementation and promotion for Social Media.</li><li class="area-list-subhead">For Individuals</li><li>Learn AI</li><li>Create a digital business</li><li>Develop your own application</li><li>Automate personal tasks</li><li>Increase productivity</li><li class="area-list-subhead">For Businesses</li><li>Digital transformation</li><li>AI strategy</li><li>Operational automation</li><li>Team training</li><li>Digital product development</li><li>AI integration into existing processes</li><li class="area-list-subhead">Why Choose Pharus AI — Complete Solution</li><li>Visual identity creation</li><li>Brand Book creation</li><li>From the company\'s initial idea to the final product and its digital promotion</li><li class="area-list-subhead">Focus on Results</li><li>Productivity</li><li>Efficiency</li><li>Growth</li>',
    fr: '<li class="area-list-subhead">Prêt à créer votre prochain projet ?</li><li>Vous souhaitez développer votre identité visuelle, votre Brand Book et l\'intégrer en créant un site web, une app, un dashboard ou un agent IA cohérents avec votre identité et marque ?</li><li>Vous souhaitez apprendre à construire des solutions numériques professionnelles en utilisant les outils les plus avancés du marché ?</li><li>Planifiez une réunion stratégique avec Pharus AI et découvrez comment transformer une idée en un produit réel, accompagné par un mentorat professionnel d\'excellence.</li><li class="area-list-subhead">Conseil Stratégique</li><li>Nous aidons à définir la meilleure stratégie technologique pour chaque situation.</li><li class="area-list-subhead">Parcours Complet</li><li>De l\'Identité Visuelle de l\'entreprise, Brand Book, au Design, à la création de site web, app ou dashboard, au Deploy et à la stratégie, mise en œuvre et diffusion sur les Réseaux Sociaux.</li><li class="area-list-subhead">Pour les Particuliers</li><li>Apprendre l\'IA</li><li>Créer un business numérique</li><li>Développer sa propre application</li><li>Automatiser les tâches personnelles</li><li>Augmenter la productivité</li><li class="area-list-subhead">Pour les Entreprises</li><li>Transformation numérique</li><li>Stratégie IA</li><li>Automatisation opérationnelle</li><li>Formation des équipes</li><li>Développement de produits numériques</li><li>Intégration de l\'IA dans les processus existants</li><li class="area-list-subhead">Pourquoi Choisir Pharus AI — Solution Complète</li><li>Création d\'identité visuelle</li><li>Création de Brand Book</li><li>De l\'idée initiale de l\'entreprise au produit final et à sa diffusion numérique</li><li class="area-list-subhead">Focus sur les Résultats</li><li>Productivité</li><li>Efficacité</li><li>Croissance</li>'
  },

  'carousel.formacao-implementacao.h3': { en: 'Training and Implementation', fr: 'Formation et Mise en Œuvre' },
  'carousel.formacao-implementacao.p':  { en: 'We don\'t just teach theory. We build with you.', fr: 'Nous n\'enseignons pas seulement la théorie. Nous construisons avec vous.' },
  'carousel.formacao-implementacao.ul': {
    en: '<li>Latest Generation Technologies — We use the best tools available on the market.</li><li>Continuous Support — Support. Evolution. Continuous improvement.</li><li class="area-list-subhead">AI and Full-Stack Development Training</li><li>Learn to create complete digital solutions</li><li>From idea to final product in production</li><li>Individual training</li><li>Team training</li><li>Personalised mentoring</li>',
    fr: '<li>Technologies de Dernière Génération — Nous utilisons les meilleurs outils disponibles sur le marché.</li><li>Accompagnement Continu — Support. Évolution. Amélioration continue.</li><li class="area-list-subhead">Formation en Intelligence Artificielle et Développement Full-Stack</li><li>Apprendre à créer des solutions numériques complètes</li><li>De l\'idée au produit final en production</li><li>Formation individuelle</li><li>Formation pour équipes</li><li>Mentorat personnalisé</li>'
  },

  'carousel.servicos-pharus.h3': { en: 'Pharus AI Services', fr: 'Services Pharus AI' },
  'carousel.servicos-pharus.p':  { en: 'We transform Ideas into Intelligent Digital Solutions', fr: 'Nous transformons les Idées en Solutions Numériques Intelligentes' },
  'carousel.servicos-pharus.ul': {
    en: '<li>Pharus AI helps individuals and businesses create modern digital products</li><li>From the initial idea through to production launch</li><li>Autonomous Agents</li><li>Business Copilots</li><li>Intelligent Chatbots</li><li>RAG Systems</li><li>Model Fine-Tuning</li><li>Advanced Prompt Engineering</li><li>Process Automation</li><li>AI-as-a-Service</li><li class="area-list-subhead">Our goal is simple</li><li>To put in your hands the tools and knowledge to create, sell and scale digital businesses.</li>',
    fr: '<li>Pharus AI aide les particuliers et les entreprises à créer des produits numériques modernes</li><li>De l\'idée initiale au lancement en production</li><li>Agents Autonomes</li><li>Copilotos d\'Entreprise</li><li>Chatbots Intelligents</li><li>Systèmes RAG</li><li>Fine-Tuning de Modèles</li><li>Prompt Engineering Avancé</li><li>Automatisation des Processus</li><li>AI-as-a-Service</li><li class="area-list-subhead">Notre objectif est simple</li><li>Mettre entre vos mains les outils et les connaissances pour créer, vendre et faire évoluer des entreprises numériques.</li>'
  },

  'carousel.dev-websites.h3': { en: 'Website Development', fr: 'Développement de Sites Web' },
  'carousel.dev-websites.p':  { en: 'We create modern, fast websites designed to convert visitors into clients.', fr: 'Nous créons des sites web modernes, rapides et conçus pour convertir les visiteurs en clients.' },
  'carousel.dev-websites.ul': {
    en: '<li class="area-list-subhead">What we develop</li><li>Web applications</li><li>Mobile apps</li><li>Artificial Intelligence agents</li><li>Automations</li><li>Professional blogs</li><li>Business dashboards</li><li>We train teams to master the technologies transforming the market</li><li>Integrations</li><li>High-conversion Landing Pages</li><li>Marketplaces</li><li>Service platforms</li><li>Business portals</li><li>Personal brand websites</li><li>Corporate websites</li><li>Institutional websites</li><li class="area-list-subhead">Includes</li><li>Analytics and monitoring</li><li>Professional UX/UI design</li><li>Deploy and maintenance</li><li>Responsive development</li><li>Smart forms</li><li>AI integration</li><li>CRM integration</li><li>Technical SEO</li>',
    fr: '<li class="area-list-subhead">Ce que nous développons</li><li>Applications web</li><li>Applications mobiles</li><li>Agents d\'Intelligence Artificielle</li><li>Automatisations</li><li>Blogs professionnels</li><li>Tableaux de bord d\'entreprise</li><li>Nous formons les équipes pour maîtriser les technologies qui transforment le marché</li><li>Intégrations</li><li>Landing Pages à haute conversion</li><li>Marketplaces</li><li>Plateformes de services</li><li>Portails d\'entreprise</li><li>Sites web pour marques personnelles</li><li>Sites web d\'entreprise</li><li>Sites web institutionnels</li><li class="area-list-subhead">Inclut</li><li>Analytique et surveillance</li><li>Design professionnel UX/UI</li><li>Déploiement et maintenance</li><li>Développement responsive</li><li>Formulaires intelligents</li><li>Intégration avec IA</li><li>Intégration avec CRM</li><li>SEO technique</li>'
  },

  'carousel.dev-aplicacoes-web.h3': { en: 'Web Application Development', fr: 'Développement d\'Applications Web' },
  'carousel.dev-aplicacoes-web.p':  { en: 'We create custom web applications to solve specific problems and increase productivity.', fr: 'Nous créons des applications web sur mesure pour résoudre des problèmes spécifiques et augmenter la productivité.' },
  'carousel.dev-aplicacoes-web.ul': {
    en: '<li class="area-list-subhead">Examples</li><li>Custom CRMs</li><li>Specialised ERPs</li><li>E-learning platforms</li><li>SaaS platforms</li><li>Client portals</li><li>Automation tools</li><li>Internal management systems</li><li>Booking systems</li><li class="area-list-subhead">Technology</li><li>Modern APIs</li><li>Cloud Computing</li><li>Java</li><li>Next.js</li><li>Node.js</li><li>Python</li><li>React</li><li>SQL</li>',
    fr: '<li class="area-list-subhead">Exemples</li><li>CRMs personnalisés</li><li>ERPs spécialisés</li><li>Plateformes e-learning</li><li>Plateformes SaaS</li><li>Portails clients</li><li>Outils d\'automatisation</li><li>Systèmes de gestion interne</li><li>Systèmes de réservation</li><li class="area-list-subhead">Technologie</li><li>APIs modernes</li><li>Cloud Computing</li><li>Java</li><li>Next.js</li><li>Node.js</li><li>Python</li><li>React</li><li>SQL</li>'
  },

  'carousel.dev-apps-mobile.h3': { en: 'Mobile App Development', fr: 'Développement d\'Applications Mobiles' },
  'carousel.dev-apps-mobile.p':  { en: 'We transform ideas into mobile applications for Android and iPhone.', fr: 'Nous transformons les idées en applications mobiles pour Android et iPhone.' },
  'carousel.dev-apps-mobile.ul': {
    en: '<li class="area-list-subhead">We create</li><li>Business apps</li><li>Productivity apps</li><li>Educational apps</li><li>Health apps</li><li>Real estate apps</li><li>Renewable energy apps</li><li>Sales team apps</li><li>Apps with integrated Artificial Intelligence</li><li class="area-list-subhead">Features</li><li>AI assistants</li><li>Intelligent chatbots</li><li>Mobile dashboards</li><li>Geolocation</li><li>API integration</li><li>Secure login</li><li>Push notifications</li>',
    fr: '<li class="area-list-subhead">Nous créons</li><li>Applications d\'entreprise</li><li>Applications de productivité</li><li>Applications éducatives</li><li>Applications de santé</li><li>Applications immobilières</li><li>Applications pour les énergies renouvelables</li><li>Applications pour équipes commerciales</li><li>Applications avec Intelligence Artificielle intégrée</li><li class="area-list-subhead">Fonctionnalités</li><li>Assistants IA</li><li>Chatbots intelligents</li><li>Tableaux de bord mobiles</li><li>Géolocalisation</li><li>Intégration avec APIs</li><li>Connexion sécurisée</li><li>Notifications push</li>'
  },

  'carousel.dashboards.h3': { en: 'Business Dashboards', fr: 'Tableaux de Bord d\'Entreprise' },
  'carousel.dashboards.p':  { en: 'Data only has value when it drives decisions. We create executive dashboards that transform scattered information into clear indicators.', fr: 'Les données n\'ont de valeur que lorsqu\'elles génèrent des décisions. Nous créons des tableaux de bord exécutifs qui transforment les informations dispersées en indicateurs clairs.' },
  'carousel.dashboards.ul': {
    en: '<li class="area-list-subhead">We develop Dashboards</li><li>Marketing</li><li>HR</li><li>Sales</li><li>Energy</li><li>Financial</li><li>Real estate</li><li>Operational</li><li>For AI</li><li class="area-list-subhead">Benefits</li><li>Interactive charts</li><li>Real-time information</li><li>Integration with multiple data sources</li><li>Centralised KPIs</li><li>Automatic reports</li>',
    fr: '<li class="area-list-subhead">Nous développons des Tableaux de Bord</li><li>Marketing</li><li>RH</li><li>Ventes</li><li>Énergie</li><li>Finance</li><li>Immobilier</li><li>Opérationnel</li><li>Pour l\'IA</li><li class="area-list-subhead">Bénéfices</li><li>Graphiques interactifs</li><li>Informations en temps réel</li><li>Intégration avec de multiples sources de données</li><li>KPIs centralisés</li><li>Rapports automatiques</li>'
  },

  'carousel.integracoes.h3': { en: 'Integration with:', fr: 'Intégration avec :' },
  'carousel.integracoes.p':  { en: 'We connect your tools and platforms to maximise operational efficiency.', fr: 'Nous connectons vos outils et plateformes pour maximiser l\'efficacité opérationnelle.' },
  'carousel.integracoes.ul': {
    en: '<li>Databases</li><li>CRM</li><li>ERP</li><li>Google Workspace</li><li>Microsoft 365</li><li>Cloud Platforms</li><li>Telegram</li><li>WhatsApp</li>',
    fr: '<li>Bases de Données</li><li>CRM</li><li>ERP</li><li>Google Workspace</li><li>Microsoft 365</li><li>Plateformes Cloud</li><li>Telegram</li><li>WhatsApp</li>'
  },

  'carousel.ia-geral.h3': { en: 'Artificial Intelligence with Real-World Application', fr: 'Intelligence Artificielle avec Application Réelle' },
  'carousel.ia-geral.p':  { en: 'Training and practical application of the most advanced AI tools on the market.', fr: 'Formation et application pratique des outils IA les plus avancés du marché.' },
  'carousel.ia-geral.ul': {
    en: '<li>Avatar – Avatar Creation</li><li>ChatGPT</li><li>ChatMistralLLM (LLM European compliant)</li><li>Claude AI</li><li>Claude Code</li><li>Claude Projects</li><li>Claude CoWork</li><li>Claude Live Artifacts</li><li>CoPilot</li><li>Deepseek</li><li>Google AI Studio</li><li>Google Anthropic + Claude Code Programming</li><li>Google Gemini</li><li>Google Stitch</li><li>Grok</li><li>LLM\'s — Use of various models applied according to need</li><li>Media – (Text, image and video) — Creation and editing</li><li>MVP – Development</li><li>Music with AI</li><li>NotebookLM</li><li>Perplexity</li><li>Podcasts – Development</li><li>Strategic use of different LLMs for different objectives</li><li>Whisper</li><li>WhisperFlow – Voice commands</li>',
    fr: '<li>Avatar – Création d\'Avatar</li><li>ChatGPT</li><li>ChatMistralLLM (LLM European compliant)</li><li>Claude AI</li><li>Claude Code</li><li>Claude Projects</li><li>Claude CoWork</li><li>Claude Live Artifacts</li><li>CoPilot</li><li>Deepseek</li><li>Google AI Studio</li><li>Google Anthropic + Claude Code Programming</li><li>Google Gemini</li><li>Google Stitch</li><li>Grok</li><li>LLM\'s — Utilisation de divers modèles appliqués selon le besoin</li><li>Média – (Texte, image et vidéo) — Création et édition</li><li>MVP – Développement</li><li>Musique avec IA</li><li>NotebookLM</li><li>Perplexity</li><li>Podcasts – Développement</li><li>Utilisation stratégique de différents LLMs pour différents objectifs</li><li>Whisper</li><li>WhisperFlow – Commandes vocales</li>'
  },

  'carousel.design-ia.h3': { en: 'AI-Assisted Design', fr: 'Design Assisté par IA' },
  'carousel.design-ia.p':  { en: 'Creation of visual identity, content and marketing assets with artificial intelligence.', fr: 'Création d\'identité visuelle, de contenu et d\'assets marketing avec l\'intelligence artificielle.' },
  'carousel.design-ia.ul': {
    en: '<li>The company can write its own brief</li><li>After obtaining the Business DNA, we suggest campaign ideas aligned with the business: seasonal themes, product launches, events, awareness campaigns</li><li>Landing page assets: hero image, feature screenshots, visual testimonials</li><li>Ad banners for user acquisition</li><li>Banners for Google Ads, launch posts for social networks and product photos for the website</li><li>Brand Book for internal documentation and partners</li><li>Content for launch campaign</li><li>Social Media asset generation</li><li>Generation of posts ready for Instagram, Facebook, X/Twitter, LinkedIn and YouTube (thumbnails)</li><li>Visual Identity for internal documentation and partners</li>',
    fr: '<li>L\'entreprise peut rédiger son propre brief</li><li>Après avoir obtenu le Business DNA, nous suggérons des idées de campagne alignées avec l\'activité : thèmes saisonniers, lancements de produits, événements, campagnes de sensibilisation</li><li>Assets de la landing page : hero image, captures d\'écran de fonctionnalités, témoignages visuels</li><li>Bannières publicitaires pour l\'acquisition d\'utilisateurs</li><li>Bannières pour Google Ads, posts de lancement pour les réseaux sociaux et photos de produits pour le site web</li><li>Brand Book pour la documentation interne et les partenaires</li><li>Contenu pour campagne de lancement</li><li>Génération d\'assets pour les Réseaux Sociaux</li><li>Génération de posts prêts pour Instagram, Facebook, X/Twitter, LinkedIn et YouTube (thumbnails)</li><li>Identité Visuelle pour la documentation interne et les partenaires</li>'
  },

  'carousel.fullstack.h3': { en: 'Full-Stack Development and Tools', fr: 'Développement Full-Stack et Outils' },
  'carousel.fullstack.p':  { en: 'Complete mastery of the modern technology stack, from next-generation tools to production deployment.', fr: 'Maîtrise complète du stack technologique moderne, des outils de nouvelle génération au déploiement en production.' },
  'carousel.fullstack.ul': {
    en: '<li class="area-list-subhead">Full-Stack Development</li><li>Databases</li><li>REST APIs</li><li>CSS3</li><li>HTML5</li><li>Java</li><li>JavaScript</li><li>Python</li><li>SQL</li><li>TypeScript</li><li class="area-list-subhead">Next-Generation Tools</li><li>Agentic AI Tools</li><li>Automation Frameworks</li><li>Google Antigravity</li><li>Google Opal</li><li>Nano Banana 2</li><li>Vercel AI</li><li class="area-list-subhead">Cloud and Deploy</li><li>CI/CD</li><li>Automated deployment</li><li>Domains</li><li>GitHub Pages</li><li>Hosting</li><li>Netlify</li><li>Vercel</li><li class="area-list-subhead">Version Control</li><li>Branching Strategies</li><li>Git</li><li>GitHub</li><li>GitHub Actions</li><li>Professional Versioning</li>',
    fr: '<li class="area-list-subhead">Développement Full-Stack</li><li>Bases de Données</li><li>APIs REST</li><li>CSS3</li><li>HTML5</li><li>Java</li><li>JavaScript</li><li>Python</li><li>SQL</li><li>TypeScript</li><li class="area-list-subhead">Outils de Nouvelle Génération</li><li>Outils Agentic AI</li><li>Frameworks d\'Automatisation</li><li>Google Antigravity</li><li>Google Opal</li><li>Nano Banana 2</li><li>Vercel AI</li><li class="area-list-subhead">Cloud et Déploiement</li><li>CI/CD</li><li>Déploiement automatisé</li><li>Domaines</li><li>GitHub Pages</li><li>Hébergement</li><li>Netlify</li><li>Vercel</li><li class="area-list-subhead">Contrôle de Versions</li><li>Branching Strategies</li><li>Git</li><li>GitHub</li><li>GitHub Actions</li><li>Versionnement Professionnel</li>'
  },

  'carousel.negocios-digitais.h3': { en: 'Digital Business Creation', fr: 'Création d\'Entreprises Numériques' },
  'carousel.negocios-digitais.p':  { en: 'From concept to launch — we transform ideas into profitable digital businesses.', fr: 'Du concept au lancement — nous transformons les idées en entreprises numériques rentables.' },
  'carousel.negocios-digitais.ul': {
    en: '<li>AI agent creation</li><li>Mobile app creation</li><li>Online course creation</li><li>Digital brand creation</li><li>SaaS creation</li><li>Professional website creation</li><li>Monetisation strategies</li>',
    fr: '<li>Création d\'agents IA</li><li>Création d\'applications mobiles</li><li>Création de cours en ligne</li><li>Création de marques numériques</li><li>Création de SaaS</li><li>Création de sites web professionnels</li><li>Stratégies de monétisation</li>'
  }
};

